name: Qodana Code Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Qodana
        uses: JetBrains/qodana-action@v2023.3
        with:
          linter: jetbrains/qodana-jvm # Thay bằng loại linter phù hợp nếu cần

      - name: Upload Qodana Report
        uses: actions/upload-artifact@v4
        with:
          name: qodana-report
          path: qodana/report
